/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/notebooks/v1/service.proto

package com.google.cloud.notebooks.v1;

public final class NotebooksProto {
  private NotebooksProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_OperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_OperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListInstancesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListInstancesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListInstancesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListInstancesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_CreateInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_CreateInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_RegisterInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_RegisterInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_SetInstanceAcceleratorRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_SetInstanceAcceleratorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_SetInstanceMachineTypeRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_SetInstanceMachineTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_UpdateInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_UpdateInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_UpdateShieldedInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_UpdateShieldedInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_DeleteInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_DeleteInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_StartInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_StartInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_StopInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_StopInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ResetInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ResetInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_HealthInfoEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_HealthInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_UpgradeInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_UpgradeInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_RollbackInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_RollbackInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_UpgradeInstanceInternalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_UpgradeInstanceInternalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListEnvironmentsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListEnvironmentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListEnvironmentsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListEnvironmentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_CreateEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_CreateEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_DeleteEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_DeleteEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListSchedulesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListSchedulesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListSchedulesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListSchedulesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetScheduleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_DeleteScheduleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_DeleteScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_CreateScheduleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_CreateScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_TriggerScheduleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_TriggerScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListExecutionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListExecutionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_ListExecutionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_ListExecutionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_GetExecutionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_GetExecutionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_DeleteExecutionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_DeleteExecutionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_notebooks_v1_CreateExecutionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_notebooks_v1_CreateExecutionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "\'google/cloud/notebooks/v1/service.prot"
          + "o\022\031google.cloud.notebooks.v1\032\034google/api"
          + "/annotations.proto\032\027google/api/client.pr"
          + "oto\032\037google/api/field_behavior.proto\032\031go"
          + "ogle/api/resource.proto\032+google/cloud/notebooks/v1/environment.proto\032)google/clo"
          + "ud/notebooks/v1/execution.proto\032(google/cloud/notebooks/v1/instance.proto\032/googl"
          + "e/cloud/notebooks/v1/instance_config.proto\032(google/cloud/notebooks/v1/schedule.p"
          + "roto\032#google/longrunning/operations.proto\032\037google/protobuf/timestamp.proto\"\357\001\n"
          + "\021OperationMetadata\022/\n"
          + "\013create_time\030\001 \001(\0132\032.google.protobuf.Timestamp\022,\n"
          + "\010end_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022\016\n"
          + "\006target\030\003 \001(\t\022\014\n"
          + "\004verb\030\004 \001(\t\022\026\n"
          + "\016status_message\030\005 \001(\t\022\036\n"
          + "\026requested_cancellation\030\006 \001(\010\022\023\n"
          + "\013api_version\030\007 \001(\t\022\020\n"
          + "\010endpoint\030\010 \001(\t\"R\n"
          + "\024ListInstancesRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\"}\n"
          + "\025ListInstancesResponse\0226\n"
          + "\tinstances\030\001 \003(\0132#.google.cloud.notebooks.v1.Instance\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"\'\n"
          + "\022GetInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"\202\001\n"
          + "\025CreateInstanceRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\030\n"
          + "\013instance_id\030\002 \001(\tB\003\340A\002\022:\n"
          + "\010instance\030\003 \001(\0132#.google.cloud.notebooks.v1.InstanceB\003\340A\002\"H\n"
          + "\027RegisterInstanceRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\030\n"
          + "\013instance_id\030\002 \001(\tB\003\340A\002\"\223\001\n"
          + "\035SetInstanceAcceleratorRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022F\n"
          + "\004type\030\002 \001"
          + "(\01623.google.cloud.notebooks.v1.Instance.AcceleratorTypeB\003\340A\002\022\027\n\n"
          + "core_count\030\003 \001(\003B\003\340A\002\"M\n"
          + "\035SetInstanceMachineTypeRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\031\n"
          + "\014machine_type\030\002 \001(\tB\003\340A\002\"k\n"
          + "\033UpdateInstanceConfigRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\0229\n"
          + "\006config\030\002 \001(\0132).google.cloud.notebooks.v1.InstanceConfig\"\255\001\n"
          + "\030SetInstanceLabelsRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022O\n"
          + "\006labels\030\002 \003(\0132?.google.cloud.noteboo"
          + "ks.v1.SetInstanceLabelsRequest.LabelsEntry\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\226\001\n"
          + "#UpdateShieldedInstanceConfigRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\\\n"
          + "\030shielded_instance_config\030\002 \001(\0132:.google.cloud.no"
          + "tebooks.v1.Instance.ShieldedInstanceConfig\"*\n"
          + "\025DeleteInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\")\n"
          + "\024StartInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"(\n"
          + "\023StopInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\")\n"
          + "\024ResetInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"\311\001\n"
          + "\031ReportInstanceInfoRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\022\n"
          + "\005vm_id\030\002 \001(\tB\003\340A\002\022T\n"
          + "\010metadata\030\003 \003(\0132B.google.cloud.not"
          + "ebooks.v1.ReportInstanceInfoRequest.MetadataEntry\032/\n\r"
          + "MetadataEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\">\n"
          + "\034IsInstanceUpgradeableRequest\022\036\n"
          + "\021notebook_instance\030\001 \001(\tB\003\340A\002\"z\n"
          + "\035IsInstanceUpgradeableResponse\022\023\n"
          + "\013upgradeable\030\001 \001(\010\022\027\n"
          + "\017upgrade_version\030\002 \001(\t\022\024\n"
          + "\014upgrade_info\030\003 \001(\t\022\025\n\r"
          + "upgrade_image\030\004 \001(\t\"S\n"
          + "\030GetInstanceHealthRequest\0227\n"
          + "\004name\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Instance\"\204\003\n"
          + "\031GetInstanceHealthResponse\022[\n"
          + "\014health_state\030\001 \001(\0162@.google.cloud.n"
          + "otebooks.v1.GetInstanceHealthResponse.HealthStateB\003\340A\003\022^\n"
          + "\013health_info\030\002 \003(\0132D.go"
          + "ogle.cloud.notebooks.v1.GetInstanceHealthResponse.HealthInfoEntryB\003\340A\003\0321\n"
          + "\017HealthInfoEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"w\n"
          + "\013HealthState\022\034\n"
          + "\030HEALTH_STATE_UNSPECIFIED\020\000\022\013\n"
          + "\007HEALTHY\020\001\022\r\n"
          + "\tUNHEALTHY\020\002\022\027\n"
          + "\023AGENT_NOT_INSTALLED\020\003\022\025\n"
          + "\021AGENT_NOT_RUNNING\020\004\"+\n"
          + "\026UpgradeInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"J\n"
          + "\027RollbackInstanceRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\034\n"
          + "\017target_snapshot\030\002 \001(\tB\003\340A\002\"G\n"
          + "\036UpgradeInstanceInternalRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\022\n"
          + "\005vm_id\030\002 \001(\tB\003\340A\002\"U\n"
          + "\027ListEnvironmentsRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\"\206\001\n"
          + "\030ListEnvironmentsResponse\022<\n"
          + "\014environments\030\001 \003(\0132&.google.cloud.notebooks.v1.Environment\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"*\n"
          + "\025GetEnvironmentRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"\216\001\n"
          + "\030CreateEnvironmentRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\033\n"
          + "\016environment_id\030\002 \001(\tB\003\340A\002\022@\n"
          + "\013environment\030\003"
          + " \001(\0132&.google.cloud.notebooks.v1.EnvironmentB\003\340A\002\"-\n"
          + "\030DeleteEnvironmentRequest\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\"\232\001\n"
          + "\024ListSchedulesRequest\0229\n"
          + "\006parent\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Schedule\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\022\016\n"
          + "\006filter\030\004 \001(\t\022\020\n"
          + "\010order_by\030\005 \001(\t\"}\n"
          + "\025ListSchedulesResponse\0226\n"
          + "\tschedules\030\001 \003(\0132#.google.cloud.notebooks.v1.Schedule\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"M\n"
          + "\022GetScheduleRequest\0227\n"
          + "\004name\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Schedule\"P\n"
          + "\025DeleteScheduleRequest\0227\n"
          + "\004name\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Schedule\"\250\001\n"
          + "\025CreateScheduleRequest\0229\n"
          + "\006parent\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Schedule\022\030\n"
          + "\013schedule_id\030\002 \001(\tB\003\340A\002\022:\n"
          + "\010schedule\030\003 \001(\0132#.google.cloud.notebooks.v1.ScheduleB\003\340A\002\"Q\n"
          + "\026TriggerScheduleRequest\0227\n"
          + "\004name\030\001 \001(\tB)\340A\002\372A#\n"
          + "!notebooks.googleapis.com/Schedule\"\234\001\n"
          + "\025ListExecutionsRequest\022:\n"
          + "\006parent\030\001 \001(\tB*\340A\002\372A$\n"
          + "\"notebooks.googleapis.com/Execution\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\022\016\n"
          + "\006filter\030\004 \001(\t\022\020\n"
          + "\010order_by\030\005 \001(\t\"\200\001\n"
          + "\026ListExecutionsResponse\0228\n\n"
          + "executions\030\001 \003(\0132$.google.cloud.notebooks.v1.Execution\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"O\n"
          + "\023GetExecutionRequest\0228\n"
          + "\004name\030\001 \001(\tB*\340A\002\372A$\n"
          + "\"notebooks.googleapis.com/Execution\"R\n"
          + "\026DeleteExecutionRequest\0228\n"
          + "\004name\030\001 \001(\tB*\340A\002\372A$\n"
          + "\"notebooks.googleapis.com/Execution\"\255\001\n"
          + "\026CreateExecutionRequest\022:\n"
          + "\006parent\030\001 \001(\tB*\340A\002\372A$\n"
          + "\"notebooks.googleapis.com/Execution\022\031\n"
          + "\014execution_id\030\002 \001(\tB\003\340A\002\022<\n"
          + "\texecution\030\003"
          + " \001(\0132$.google.cloud.notebooks.v1.ExecutionB\003\340A\0022\3513\n"
          + "\017NotebookService\022\262\001\n\r"
          + "ListInstances\022/.google.cloud.notebooks.v1.ListInstancesRequest\0320.goog"
          + "le.cloud.notebooks.v1.ListInstancesRespo"
          + "nse\">\202\323\344\223\002/\022-/v1/{parent=projects/*/locations/*}/instances\332A\006parent\022\237\001\n"
          + "\013GetInstance\022-.google.cloud.notebooks.v1.GetInsta"
          + "nceRequest\032#.google.cloud.notebooks.v1.I"
          + "nstance\"<\202\323\344\223\002/\022-/v1/{name=projects/*/locations/*/instances/*}\332A\004name\022\340\001\n"
          + "\016CreateInstance\0220.google.cloud.notebooks.v1.Cre"
          + "ateInstanceRequest\032\035.google.longrunning."
          + "Operation\"}\202\323\344\223\0029\"-/v1/{parent=projects/"
          + "*/locations/*}/instances:\010instance\332A\033parent,instance,instance_id\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\310\001\n"
          + "\020RegisterInstance\0222.google.cloud.notebooks.v1.RegisterInstan"
          + "ceRequest\032\035.google.longrunning.Operation"
          + "\"a\202\323\344\223\002;\"6/v1/{parent=projects/*/locations/*}/instances:register:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\332\001\n"
          + "\026SetInstanceAccelerator\0228.google.cloud.notebooks.v1.SetIn"
          + "stanceAcceleratorRequest\032\035.google.longru"
          + "nning.Operation\"g\202\323\344\223\002A2</v1/{name=proje"
          + "cts/*/locations/*/instances/*}:setAccelerator:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\332\001\n"
          + "\026SetInstanceMachineType\0228.google.cloud.notebooks.v1.SetInstanceMachineTypeRe"
          + "quest\032\035.google.longrunning.Operation\"g\202\323"
          + "\344\223\002A2</v1/{name=projects/*/locations/*/instances/*}:setMachineType:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\324\001\n"
          + "\024UpdateInstanceConfig\0226.google.cloud.notebooks.v1.Updat"
          + "eInstanceConfigRequest\032\035.google.longrunn"
          + "ing.Operation\"e\202\323\344\223\002?2:/v1/{name=project"
          + "s/*/locations/*/instances/*}:updateConfig:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\364\001\n"
          + "\034UpdateShieldedInstanceConfig\022>.google.cloud.notebooks.v1.UpdateShieldedInstance"
          + "ConfigRequest\032\035.google.longrunning.Opera"
          + "tion\"u\202\323\344\223\002O2J/v1/{name=projects/*/locat"
          + "ions/*/instances/*}:updateShieldedInstanceConfig:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\313\001\n"
          + "\021SetInstanceLabels\0223.google.cloud.notebooks.v1.SetInstanceLabelsRequest\032\035"
          + ".google.longrunning.Operation\"b\202\323\344\223\002<27/"
          + "v1/{name=projects/*/locations/*/instances/*}:setLabels:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\314\001\n"
          + "\016DeleteInstance\0220.google.cloud.notebooks.v1.DeleteInstanceRequest\032\035"
          + ".google.longrunning.Operation\"i\202\323\344\223\002/*-/"
          + "v1/{name=projects/*/locations/*/instances/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\277\001\n\r"
          + "StartInstance\022/.google.cloud.notebooks.v1.StartInstanceRequ"
          + "est\032\035.google.longrunning.Operation\"^\202\323\344\223"
          + "\0028\"3/v1/{name=projects/*/locations/*/instances/*}:start:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\274\001\n"
          + "\014StopInstance\022..google.cloud.notebooks.v1.StopInstanceRequest\032\035.go"
          + "ogle.longrunning.Operation\"]\202\323\344\223\0027\"2/v1/"
          + "{name=projects/*/locations/*/instances/*}:stop:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\277\001\n\r"
          + "ResetInstance\022/.google.cloud.notebooks.v1.ResetInstanceRequest\032\035.google.lo"
          + "ngrunning.Operation\"^\202\323\344\223\0028\"3/v1/{name=p"
          + "rojects/*/locations/*/instances/*}:reset:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\312\001\n"
          + "\022ReportInstanceInfo\0224.google.cloud.notebo"
          + "oks.v1.ReportInstanceInfoRequest\032\035.googl"
          + "e.longrunning.Operation\"_\202\323\344\223\0029\"4/v1/{na"
          + "me=projects/*/locations/*/instances/*}:report:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\334\001\n"
          + "\025IsInstanceUpgradeable\0227.google.cloud.notebooks.v1.IsInstanceUpgradeableRequ"
          + "est\0328.google.cloud.notebooks.v1.IsInstan"
          + "ceUpgradeableResponse\"P\202\323\344\223\002J\022H/v1/{note"
          + "book_instance=projects/*/locations/*/instances/*}:isUpgradeable\022\316\001\n"
          + "\021GetInstanceHealth\0223.google.cloud.notebooks.v1.GetIns"
          + "tanceHealthRequest\0324.google.cloud.notebo"
          + "oks.v1.GetInstanceHealthResponse\"N\202\323\344\223\002A"
          + "\022?/v1/{name=projects/*/locations/*/instances/*}:getInstanceHealth\332A\004name\022\305\001\n"
          + "\017UpgradeInstance\0221.google.cloud.notebooks.v1"
          + ".UpgradeInstanceRequest\032\035.google.longrun"
          + "ning.Operation\"`\202\323\344\223\002:\"5/v1/{name=projec"
          + "ts/*/locations/*/instances/*}:upgrade:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\310\001\n"
          + "\020RollbackInstance\0222.google.cloud.notebooks.v"
          + "1.RollbackInstanceRequest\032\035.google.longr"
          + "unning.Operation\"a\202\323\344\223\002;\"6/v1/{name=proj"
          + "ects/*/locations/*/instances/*}:rollback:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\335\001\n"
          + "\027UpgradeInstanceInternal\0229.google.cloud.n"
          + "otebooks.v1.UpgradeInstanceInternalReque"
          + "st\032\035.google.longrunning.Operation\"h\202\323\344\223\002"
          + "B\"=/v1/{name=projects/*/locations/*/instances/*}:upgradeInternal:\001*\312A\035\n"
          + "\010Instance\022\021OperationMetadata\022\276\001\n"
          + "\020ListEnvironments\0222.google.cloud.notebooks.v1.ListEnviron"
          + "mentsRequest\0323.google.cloud.notebooks.v1"
          + ".ListEnvironmentsResponse\"A\202\323\344\223\0022\0220/v1/{"
          + "parent=projects/*/locations/*}/environments\332A\006parent\022\253\001\n"
          + "\016GetEnvironment\0220.google.cloud.notebooks.v1.GetEnvironmentReques"
          + "t\032&.google.cloud.notebooks.v1.Environmen"
          + "t\"?\202\323\344\223\0022\0220/v1/{name=projects/*/locations/*/environments/*}\332A\004name\022\366\001\n"
          + "\021CreateEnvironment\0223.google.cloud.notebooks.v1.Cre"
          + "ateEnvironmentRequest\032\035.google.longrunni"
          + "ng.Operation\"\214\001\202\323\344\223\002?\"0/v1/{parent=proje"
          + "cts/*/locations/*}/environments:\013environ"
          + "ment\332A!parent,environment,environment_id\312A \n"
          + "\013Environment\022\021OperationMetadata\022\325\001\n"
          + "\021DeleteEnvironment\0223.google.cloud.noteboo"
          + "ks.v1.DeleteEnvironmentRequest\032\035.google."
          + "longrunning.Operation\"l\202\323\344\223\0022*0/v1/{name"
          + "=projects/*/locations/*/environments/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\262\001\n\r"
          + "ListSchedules\022/.google.cloud.notebooks.v1.ListSchedulesRequest\0320"
          + ".google.cloud.notebooks.v1.ListSchedules"
          + "Response\">\202\323\344\223\002/\022-/v1/{parent=projects/*/locations/*}/schedules\332A\006parent\022\237\001\n"
          + "\013GetSchedule\022-.google.cloud.notebooks.v1.Get"
          + "ScheduleRequest\032#.google.cloud.notebooks"
          + ".v1.Schedule\"<\202\323\344\223\002/\022-/v1/{name=projects/*/locations/*/schedules/*}\332A\004name\022\314\001\n"
          + "\016DeleteSchedule\0220.google.cloud.notebooks.v"
          + "1.DeleteScheduleRequest\032\035.google.longrun"
          + "ning.Operation\"i\202\323\344\223\002/*-/v1/{name=projects/*/locations/*/schedules/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\340\001\n"
          + "\016CreateSchedule\0220.google.cloud.note"
          + "books.v1.CreateScheduleRequest\032\035.google."
          + "longrunning.Operation\"}\202\323\344\223\0029\"-/v1/{pare"
          + "nt=projects/*/locations/*}/schedules:\010schedule\332A\033parent,schedule,schedule_id\312A\035\n"
          + "\010Schedule\022\021OperationMetadata\022\305\001\n"
          + "\017TriggerSchedule\0221.google.cloud.notebooks.v1.Tri"
          + "ggerScheduleRequest\032\035.google.longrunning"
          + ".Operation\"`\202\323\344\223\002:\"5/v1/{name=projects/*/locations/*/schedules/*}:trigger:\001*\312A\035\n"
          + "\010Schedule\022\021OperationMetadata\022\266\001\n"
          + "\016ListExecutions\0220.google.cloud.notebooks.v1.List"
          + "ExecutionsRequest\0321.google.cloud.noteboo"
          + "ks.v1.ListExecutionsResponse\"?\202\323\344\223\0020\022./v"
          + "1/{parent=projects/*/locations/*}/executions\332A\006parent\022\243\001\n"
          + "\014GetExecution\022..google.cloud.notebooks.v1.GetExecutionRequest\032$"
          + ".google.cloud.notebooks.v1.Execution\"=\202\323"
          + "\344\223\0020\022./v1/{name=projects/*/locations/*/executions/*}\332A\004name\022\317\001\n"
          + "\017DeleteExecution\0221.google.cloud.notebooks.v1.DeleteExecut"
          + "ionRequest\032\035.google.longrunning.Operatio"
          + "n\"j\202\323\344\223\0020*./v1/{name=projects/*/locations/*/executions/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\350\001\n"
          + "\017CreateExecution\0221.google.cloud.notebooks.v1.Cr"
          + "eateExecutionRequest\032\035.google.longrunnin"
          + "g.Operation\"\202\001\202\323\344\223\002;\"./v1/{parent=projects/*/locations/*}/executions:"
          + "\texecution\332A\035parent,execution,execution_id\312A\036\n"
          + "\tExecution\022\021OperationMetadata\032L\312A\030notebooks.g"
          + "oogleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\314\001\n"
          + "\035com.google.cloud.notebooks.v1B\016NotebooksProtoP\001ZBgoog"
          + "le.golang.org/genproto/googleapis/cloud/"
          + "notebooks/v1;notebooks\252\002\031Google.Cloud.No"
          + "tebooks.V1\312\002\031Google\\Cloud\\Notebooks\\V1\352\002"
          + "\034Google::Cloud::Notebooks::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.notebooks.v1.EnvironmentProto.getDescriptor(),
              com.google.cloud.notebooks.v1.ExecutionProto.getDescriptor(),
              com.google.cloud.notebooks.v1.InstanceProto.getDescriptor(),
              com.google.cloud.notebooks.v1.InstanceConfigProto.getDescriptor(),
              com.google.cloud.notebooks.v1.ScheduleProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_notebooks_v1_OperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_notebooks_v1_OperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_OperationMetadata_descriptor,
            new java.lang.String[] {
              "CreateTime",
              "EndTime",
              "Target",
              "Verb",
              "StatusMessage",
              "RequestedCancellation",
              "ApiVersion",
              "Endpoint",
            });
    internal_static_google_cloud_notebooks_v1_ListInstancesRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_notebooks_v1_ListInstancesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListInstancesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_cloud_notebooks_v1_ListInstancesResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_notebooks_v1_ListInstancesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListInstancesResponse_descriptor,
            new java.lang.String[] {
              "Instances", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_notebooks_v1_GetInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_notebooks_v1_GetInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_CreateInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_notebooks_v1_CreateInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_CreateInstanceRequest_descriptor,
            new java.lang.String[] {
              "Parent", "InstanceId", "Instance",
            });
    internal_static_google_cloud_notebooks_v1_RegisterInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_notebooks_v1_RegisterInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_RegisterInstanceRequest_descriptor,
            new java.lang.String[] {
              "Parent", "InstanceId",
            });
    internal_static_google_cloud_notebooks_v1_SetInstanceAcceleratorRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_notebooks_v1_SetInstanceAcceleratorRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_SetInstanceAcceleratorRequest_descriptor,
            new java.lang.String[] {
              "Name", "Type", "CoreCount",
            });
    internal_static_google_cloud_notebooks_v1_SetInstanceMachineTypeRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_notebooks_v1_SetInstanceMachineTypeRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_SetInstanceMachineTypeRequest_descriptor,
            new java.lang.String[] {
              "Name", "MachineType",
            });
    internal_static_google_cloud_notebooks_v1_UpdateInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_notebooks_v1_UpdateInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_UpdateInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "Name", "Config",
            });
    internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_descriptor,
            new java.lang.String[] {
              "Name", "Labels",
            });
    internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_LabelsEntry_descriptor =
        internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_SetInstanceLabelsRequest_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_notebooks_v1_UpdateShieldedInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_notebooks_v1_UpdateShieldedInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_UpdateShieldedInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "Name", "ShieldedInstanceConfig",
            });
    internal_static_google_cloud_notebooks_v1_DeleteInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_notebooks_v1_DeleteInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_DeleteInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_StartInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_notebooks_v1_StartInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_StartInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_StopInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_notebooks_v1_StopInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_StopInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_ResetInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_notebooks_v1_ResetInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ResetInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_descriptor,
            new java.lang.String[] {
              "Name", "VmId", "Metadata",
            });
    internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_MetadataEntry_descriptor =
        internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ReportInstanceInfoRequest_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableRequest_descriptor,
            new java.lang.String[] {
              "NotebookInstance",
            });
    internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_IsInstanceUpgradeableResponse_descriptor,
            new java.lang.String[] {
              "Upgradeable", "UpgradeVersion", "UpgradeInfo", "UpgradeImage",
            });
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetInstanceHealthRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_descriptor,
            new java.lang.String[] {
              "HealthState", "HealthInfo",
            });
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_HealthInfoEntry_descriptor =
        internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_HealthInfoEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetInstanceHealthResponse_HealthInfoEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_notebooks_v1_UpgradeInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_notebooks_v1_UpgradeInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_UpgradeInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_RollbackInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_notebooks_v1_RollbackInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_RollbackInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name", "TargetSnapshot",
            });
    internal_static_google_cloud_notebooks_v1_UpgradeInstanceInternalRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_notebooks_v1_UpgradeInstanceInternalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_UpgradeInstanceInternalRequest_descriptor,
            new java.lang.String[] {
              "Name", "VmId",
            });
    internal_static_google_cloud_notebooks_v1_ListEnvironmentsRequest_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_notebooks_v1_ListEnvironmentsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListEnvironmentsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_cloud_notebooks_v1_ListEnvironmentsResponse_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_notebooks_v1_ListEnvironmentsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListEnvironmentsResponse_descriptor,
            new java.lang.String[] {
              "Environments", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_notebooks_v1_GetEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_notebooks_v1_GetEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_CreateEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_notebooks_v1_CreateEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_CreateEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Parent", "EnvironmentId", "Environment",
            });
    internal_static_google_cloud_notebooks_v1_DeleteEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_notebooks_v1_DeleteEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_DeleteEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_ListSchedulesRequest_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_notebooks_v1_ListSchedulesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListSchedulesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_notebooks_v1_ListSchedulesResponse_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_notebooks_v1_ListSchedulesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListSchedulesResponse_descriptor,
            new java.lang.String[] {
              "Schedules", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_notebooks_v1_GetScheduleRequest_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_notebooks_v1_GetScheduleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetScheduleRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_DeleteScheduleRequest_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_notebooks_v1_DeleteScheduleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_DeleteScheduleRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_CreateScheduleRequest_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_notebooks_v1_CreateScheduleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_CreateScheduleRequest_descriptor,
            new java.lang.String[] {
              "Parent", "ScheduleId", "Schedule",
            });
    internal_static_google_cloud_notebooks_v1_TriggerScheduleRequest_descriptor =
        getDescriptor().getMessageTypes().get(33);
    internal_static_google_cloud_notebooks_v1_TriggerScheduleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_TriggerScheduleRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_ListExecutionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(34);
    internal_static_google_cloud_notebooks_v1_ListExecutionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListExecutionsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_notebooks_v1_ListExecutionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(35);
    internal_static_google_cloud_notebooks_v1_ListExecutionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_ListExecutionsResponse_descriptor,
            new java.lang.String[] {
              "Executions", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_notebooks_v1_GetExecutionRequest_descriptor =
        getDescriptor().getMessageTypes().get(36);
    internal_static_google_cloud_notebooks_v1_GetExecutionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_GetExecutionRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_DeleteExecutionRequest_descriptor =
        getDescriptor().getMessageTypes().get(37);
    internal_static_google_cloud_notebooks_v1_DeleteExecutionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_DeleteExecutionRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_notebooks_v1_CreateExecutionRequest_descriptor =
        getDescriptor().getMessageTypes().get(38);
    internal_static_google_cloud_notebooks_v1_CreateExecutionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_notebooks_v1_CreateExecutionRequest_descriptor,
            new java.lang.String[] {
              "Parent", "ExecutionId", "Execution",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.notebooks.v1.EnvironmentProto.getDescriptor();
    com.google.cloud.notebooks.v1.ExecutionProto.getDescriptor();
    com.google.cloud.notebooks.v1.InstanceProto.getDescriptor();
    com.google.cloud.notebooks.v1.InstanceConfigProto.getDescriptor();
    com.google.cloud.notebooks.v1.ScheduleProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
