// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/notebooks/v1/event.proto

package com.google.cloud.notebooks.v1;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.notebooks.v1.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Event report time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp report_time = 1;</code>
   * @return Whether the reportTime field is set.
   */
  boolean hasReportTime();
  /**
   * <pre>
   * Event report time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp report_time = 1;</code>
   * @return The reportTime.
   */
  com.google.protobuf.Timestamp getReportTime();
  /**
   * <pre>
   * Event report time.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp report_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getReportTimeOrBuilder();

  /**
   * <pre>
   * Event type.
   * </pre>
   *
   * <code>.google.cloud.notebooks.v1.Event.EventType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Event type.
   * </pre>
   *
   * <code>.google.cloud.notebooks.v1.Event.EventType type = 2;</code>
   * @return The type.
   */
  com.google.cloud.notebooks.v1.Event.EventType getType();
}
